### ISSUE TITLE
Touching vs0 files is (almost) never the best solution

### ISSUE THREAD

**Issue by CelesteBlue-dev** [GrapheneCt/Affinity-Changer#2]
Hooking https://wiki.henkaku.xyz/vita/SceProcessmgr#sceKernelCreateProcessForKernel would be maybe better.

**Comment by MatrixTitanHr** [comment]
+    +my comment, if you would use this app, and by any chance hold L to skip plugins, this will make them crash, there are probably more side effects then this...

**Comment by GrapheneCt** [comment]
Fixed in the latest version.
